In [2]:
from urllib.request import urlretrieve
archive_url = 'https://egriddata.org/sites/default/files/GSO_RNM_GIS_Network.zip'
archive_path = '/tmp/greensboro-synthetic-network.zip'
urlretrieve(archive_url, archive_path);

In [3]:
from invisibleroads_macros.disk import uncompress
archive_folder = uncompress(archive_path)
archive_folder

'/tmp/greensboro-synthetic-network'

In [4]:
from os.path import join
source_folder = join(archive_folder, 'GSO_RNM_GIS_Network', 'Rural')

In [ ]:
# ls $source_folder/*.shp

"""
DistribTransf_N.shp = Transformer
HVMVSubstation_N.shp = Substation
Line_N.shp = Line
NewConsumerGreenfield_N.shp = Meter
SwitchingDevices_N.shp = Switch
Transformer_N.shp = Transformer
VoltageRegulator_N.shp = Quality

DummyEquip.shp = X
Network_NEW_branches.shp = X
Network_NEW_nodes.shp = X
Network_nodes.shp = X
StreetMap_branches.shp = X
StreetMap_nodes.shp = X
TransSubstation_N.shp = X
"""

In [11]:
import geotable
source_path = join(source_folder, 'Line_N.shp')
t = line_table = geotable.load(source_path)
len(t)

13702

In [12]:
line_table.iloc[0]

Code                    CLineaCable(CRamaEE(): RCLV3922->S_Dummy325)
NodeA                                                     S_Dummy325
NodeB                                                       RCLV3922
NomV                                                            0.42
Len(1c)                                                        0.034
TypeOU                                                             T
Equip                                         1P_OH_Runcina_TRPLX2/0
R                                                            0.01439
X                                                            0.00321
C                                                                  0
Imax                                                             265
FR                                                           0.00337
T_Rep                                                              6
Status                                                             1
InvC                              

In [16]:
import geopy
g = geopy.GoogleV3('AIzaSyDNqc0tWzXHx_wIp1w75-XTcCk4BSphB5w').geocode
location = g('Greensboro, NC')
location

Location(Greensboro, NC, USA, (36.0726354, -79.7919754, 0.0))

In [17]:
from shapely.geometry import Point
p = Point(location.longitude, location.latitude)
p.wkt

'POINT (-79.7919754 36.0726354)'

In [18]:
from shapely.geometry import GeometryCollection
collection = GeometryCollection(t.geometries)
centroid = collection.centroid
centroid.wkt

'POINT (624270.0784724418 4006970.492551186)'

In [19]:
proj4s = open('proj4s.txt').read().splitlines()

In [20]:
import numpy as np
from geotable.projections import get_transform_shapely_geometry

source_geometry = t.geometries[0]
target_geometry = p
target_proj4 = geotable.LONGITUDE_LATITUDE_PROJ4

best_index = 0
best_distance = np.inf
for index, proj4 in enumerate(proj4s):
    f = get_transform_shapely_geometry(proj4, target_proj4)
    distance = p.distance(f(source_geometry))
    print(distance)
    if distance < best_distance:
        best_index = index
        best_distance = distance
best_proj4 = proj4s[best_index]
best_proj4

31.61676965613479
9.638351391431284
31.61676965613476
9.638333391786626
9.638351391431284
31.61676965613476
0.26383733078185956
31.61676965613476
9.63835139564786


'+proj=utm +zone=17 +ellps=GRS80 +datum=NAD83 +units=m +no_defs '

In [21]:
source_proj4 = proj4s[6]
source_geotable = geotable.load(
    source_path,
    source_proj4=best_proj4,
    target_proj4=target_proj4)
len(source_geotable)

13702

In [22]:
from shapely.geometry import GeometryCollection
collection = GeometryCollection(source_geotable.geometries)
collection.bounds

(-79.71827225092947, 36.13830085783994, -79.49956870558653, 36.30469203650488)

In [23]:
collection.centroid.wkt

'POINT (-79.60975239966413 36.20116405881477)'

In [24]:
geometry_columns = ['geometry_layer', 'geometry_proj4', 'geometry_object']

In [25]:
source_geotable[['Code', 'NomV', 'Phases'] + geometry_columns].to_geojson('line.geojson')

'x.geojson'

In [26]:
# mv line.geojson /home/rhh/Projects/appa-asset-tracker/experiments/dashboard/line.js

In [27]:
"""
# Line_N.shp = Line
NewConsumerGreenfield_N.shp = Meter
SwitchingDevices_N.shp = Switch
VoltageRegulator_N.shp = Quality
DistribTransf_N.shp = Transformer
Transformer_N.shp = Transformer
HVMVSubstation_N.shp = Substation
""";

In [92]:
import geotable
t = meter_table = geotable.load(join(source_folder, 'NewConsumerGreenfield_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t.iloc[5000]

Code                                                   RCLV4997
Phases                                                        1
NVoltLev                                                    CBT
NVolt_kV                                                   0.42
DemP_kW                                                    1.66
DemQ_kVAr                                                   0.8
Subest                                           S_nSSEE2_12.47
Feeder                            S_nSSEE2_12.47 -> S_nCCTT1622
Pinst_kW                                                   4.15
Qinst_kVAr                                                 2.01
RArea_m2                                                      0
NumLev                                                        1
Yearly_kWh                                                 9087
NumCust                                                       1
geometry_object    POINT (-79.70604860751182 36.17079942413907)
geometry_layer                          

In [95]:
# ' '.join(t.Code)

In [57]:
t['NVolt_kV'].unique()

array([ 0.42, 12.47])

In [58]:
t[['Code', 'NVolt_kV', 'Yearly_kWh'] + geometry_columns].to_geojson('meter.geojson')

'meter.geojson'

In [30]:
mv meter.geojson /home/rhh/Projects/appa-asset-tracker/experiments/dashboard/meter.js

In [31]:
t = switch_table = geotable.load(join(source_folder, 'SwitchingDevices_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t.iloc[0]

NodeA                                                    S_nSSEE2_69
NodeB                                                 S_nSSEE2_12.47
Branch                                                              
Code               Recloser(CRamaEE(): S_nSSEE2_12.47->S_nSSEE2_6...
Type                                                        Recloser
NomV_kV                                                        12.47
FailRate                                                           0
InvC                                                           60000
PMainC                                                          6000
PMainT                                                             0
CMainC                                                           600
Stage                                                            NEW
Subest                                                          True
Feeder                                                          True
geometry_object    LINESTRING (-79

In [33]:
t.geometries[0].wkt

'LINESTRING (-79.70794395058182 36.1643885486581, -79.70783131438053 36.16447748293956)'

In [34]:
t[['Code', 'Type', 'NomV_kV'] + geometry_columns].to_geojson('switch.geojson')

'switch.geojson'

In [35]:
t = quality_table = geotable.load(join(source_folder, 'VoltageRegulator_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t.iloc[0]

Code               CReguladorTension(CRamaEE(): S_nCCTT306->S_nCC...
Branch                                                             x
Rsc                                                                0
Xsc                                                                0
InvC                                                            6000
PMainC                                                         62.22
CMainC                                                             0
PMainT                                                            -1
NodeA                                                     S_nCCTT306
NodeB                                                     S_nCCTT307
Stage                                                            NEW
Tap(pu)                                                      1.01462
TapMin                                                           0.9
TapMax                                                           1.1
Y11(pu)                           

In [36]:
t[['Code', 'InvC'] + geometry_columns].to_geojson('quality.geojson')

'quality.geojson'

In [84]:
t1 = geotable.load(join(source_folder, 'DistribTransf_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t1.iloc[0]

Node                                                  S_nCCTT10
Code                                                  S_nCCTT10
NomV_kV                                                   12.47
Equip                                                         I
Size_kVA                                                     10
Energy_kWh                                                26280
Ppeak_kW                                                     10
Qpeak_kVAr                                                   10
NmaxOutputs                                                   5
InvCOut                                                       0
InvC                                                       2400
PMainC                                                    64.32
PMainT                                                      230
CMainC                                                        0
NMaxTransf                                                    2
NumTransf                               

In [85]:
t1['NomV_kV'].unique()

array([12.47])

In [89]:
t1['Code'][20:40]

20    S_nCCTT201
21    S_nCCTT202
22    S_nCCTT203
23    S_nCCTT183
24      S_nCCTT4
25    S_nCCTT232
26    S_nCCTT221
27    S_nCCTT230
28    S_nCCTT212
29    S_nCCTT215
30    S_nCCTT216
31    S_nCCTT234
32    S_nCCTT233
33    S_nCCTT205
34    S_nCCTT217
35    S_nCCTT219
36    S_nCCTT224
37    S_nCCTT240
38    S_nCCTT228
39    S_nCCTT235
Name: Code, dtype: object

In [63]:
t1_wkbs = [g.wkb for g in t.geometries]

In [64]:
# t1[['Code', 'NomV_kV'] + geometry_columns].to_geojson('quality.geojson')
t1 = t1[['Code', 'NomV_kV'] + geometry_columns]
t1[:5]

Code  NomV_kV   geometry_layer                       geometry_proj4  \
0   S_nCCTT10    12.47  DistribTransf_N  +proj=longlat +datum=WGS84 +no_defs   
1   S_nCCTT11    12.47  DistribTransf_N  +proj=longlat +datum=WGS84 +no_defs   
2  S_nCCTT191    12.47  DistribTransf_N  +proj=longlat +datum=WGS84 +no_defs   
3  S_nCCTT196    12.47  DistribTransf_N  +proj=longlat +datum=WGS84 +no_defs   
4  S_nCCTT192    12.47  DistribTransf_N  +proj=longlat +datum=WGS84 +no_defs   

                                geometry_object  
0  POINT (-79.63119032057774 36.28594431143009)  
1  POINT (-79.63080794081542 36.27978827498735)  
2   POINT (-79.59111424790544 36.1619537810446)  
3  POINT (-79.51367290603865 36.15010949672152)  
4  POINT (-79.58756846848706 36.16991358636837)

In [96]:
t2 = geotable.load(join(source_folder, 'Transformer_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t2.iloc[0]

Code                      CTrafo(CRamaEE(): S_nCCTT72->S_nCCTT72_BT)
NodeA                                                      S_nCCTT72
NodeB                                                   S_nCCTT72_BT
Vnom1                                                          12.47
Vnom2                                                          0.416
Phases                                                             1
Stage                                                            NEW
Xsc(pu)                                                         0.16
Tap(pu)                                                      1.03108
TapMin                                                           0.9
Tapax                                                            1.1
Y11(pu)                                                 (0,-6.64452)
Y12(pu)                                                 (-0,6.44424)
Y21(pu)                                                 (-0,6.44424)
Y22(pu)                           

In [49]:
t2_wkbs = [g.wkb for g in t.geometries]

In [66]:
sum(t2.Vnom1 > t2.Vnom2)

2690

In [67]:
sum(t2.Vnom1 < t2.Vnom2)

0

In [68]:
t2 = t2[['Code', 'Vnom1', 'Vnom2'] + geometry_columns]
t2[:5]

Code  Vnom1  Vnom2 geometry_layer  \
0  CTrafo(CRamaEE(): S_nCCTT72->S_nCCTT72_BT)  12.47  0.416  Transformer_N   
1  CTrafo(CRamaEE(): S_nCCTT73->S_nCCTT73_BT)  12.47  0.416  Transformer_N   
2  CTrafo(CRamaEE(): S_nCCTT64->S_nCCTT64_BT)  12.47  0.416  Transformer_N   
3  CTrafo(CRamaEE(): S_nCCTT60->S_nCCTT60_BT)  12.47  0.416  Transformer_N   
4  CTrafo(CRamaEE(): S_nCCTT61->S_nCCTT61_BT)  12.47  0.416  Transformer_N   

                        geometry_proj4  \
0  +proj=longlat +datum=WGS84 +no_defs   
1  +proj=longlat +datum=WGS84 +no_defs   
2  +proj=longlat +datum=WGS84 +no_defs   
3  +proj=longlat +datum=WGS84 +no_defs   
4  +proj=longlat +datum=WGS84 +no_defs   

                                     geometry_object  
0  LINESTRING (-79.64625671989072 36.180103285480...  
1  LINESTRING (-79.64322970915207 36.183274710092...  
2  LINESTRING (-79.6036822067453 36.1865763748528...  
3  LINESTRING (-79.65891406129413 36.188339354690...  
4  LINESTRING (-79.66117122352527 36.189276933445...

In [69]:
t2['NomV_kV'] = t2['Vnom2']
t2[:5]

Code  Vnom1  Vnom2 geometry_layer  \
0  CTrafo(CRamaEE(): S_nCCTT72->S_nCCTT72_BT)  12.47  0.416  Transformer_N   
1  CTrafo(CRamaEE(): S_nCCTT73->S_nCCTT73_BT)  12.47  0.416  Transformer_N   
2  CTrafo(CRamaEE(): S_nCCTT64->S_nCCTT64_BT)  12.47  0.416  Transformer_N   
3  CTrafo(CRamaEE(): S_nCCTT60->S_nCCTT60_BT)  12.47  0.416  Transformer_N   
4  CTrafo(CRamaEE(): S_nCCTT61->S_nCCTT61_BT)  12.47  0.416  Transformer_N   

                        geometry_proj4  \
0  +proj=longlat +datum=WGS84 +no_defs   
1  +proj=longlat +datum=WGS84 +no_defs   
2  +proj=longlat +datum=WGS84 +no_defs   
3  +proj=longlat +datum=WGS84 +no_defs   
4  +proj=longlat +datum=WGS84 +no_defs   

                                     geometry_object  NomV_kV  
0  LINESTRING (-79.64625671989072 36.180103285480...    0.416  
1  LINESTRING (-79.64322970915207 36.183274710092...    0.416  
2  LINESTRING (-79.6036822067453 36.1865763748528...    0.416  
3  LINESTRING (-79.65891406129413 36.188339354690...    0.416  
4  LINESTRING (-79.66117122352527 36.189276933445...    0.416

In [81]:
t2['geometry_object'] = [x.centroid for x in t2.geometries]

In [83]:
t2.save_shp('t2.shp.zip')

't2.shp.zip'

In [74]:
count = 0
for g in t2.geometries:
    if g.length > 0:
        count += 1
        print(g.wkt)
        print(g.length)
count

LINESTRING (-79.60602633795695 36.30378211314572, -79.63505549806237 36.20536376246419)
0.10261025234984246


1

In [76]:
import pandas as pd
# pd.concat([t1, t2], sort=False)

In [43]:
t['Vnom1'].unique()

array([ 12.47,  69.  , 230.  ])

In [44]:
t['Vnom2'].unique()

array([ 0.416, 12.47 , 69.   ])

In [51]:
set(t1_wkbs).intersection(t2_wkbs)

set()

In [75]:
t = distribution_transformer_table = geotable.load(join(source_folder, 'HVMVSubstation_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t.iloc[0]

Node                                                   S_nSSEE0
Code                                                   S_nSSEE0
Equip                                                  Blindada
InvC                                                3.58624e+06
PMainC                                                  96111.3
CMainC                                                      230
VNom                                                       0.00
MVA                                               ;69kV;12.47kV
NumTransf                                                     0
geometry_object    POINT (-79.60684769101411 36.19285069559501)
geometry_layer                                 HVMVSubstation_N
geometry_proj4              +proj=longlat +datum=WGS84 +no_defs
Name: 0, dtype: object

In [79]:
t['NumTransf'].unique()

array([0])

In [80]:
t[['Code'] + geometry_columns].to_geojson('substation.geojson')

'substation.geojson'

In [97]:
len(t1)

2686

In [98]:
len(t2)

2690

In [99]:
t2 = geotable.load(join(source_folder, 'Transformer_N.shp'), source_proj4=best_proj4, target_proj4=target_proj4)
t2.iloc[0]

Code                      CTrafo(CRamaEE(): S_nCCTT72->S_nCCTT72_BT)
NodeA                                                      S_nCCTT72
NodeB                                                   S_nCCTT72_BT
Vnom1                                                          12.47
Vnom2                                                          0.416
Phases                                                             1
Stage                                                            NEW
Xsc(pu)                                                         0.16
Tap(pu)                                                      1.03108
TapMin                                                           0.9
Tapax                                                            1.1
Y11(pu)                                                 (0,-6.64452)
Y12(pu)                                                 (-0,6.44424)
Y21(pu)                                                 (-0,6.44424)
Y22(pu)                           

In [100]:
from shapely.geometry import Point
t2['geometry_object'] = [Point(x.coords[0]) for x in t2.geometries]

In [102]:
t2[['Code', 'Vnom1', 'Vnom2'] + geometry_columns].to_geojson('transformer.geojson')

'transformer.geojson'