In [5]:
archive_url = (
    'https://egriddata.org/sites/default/files/'
    'GSO_RNM_GIS_Network.zip')
archive_url

'https://egriddata.org/sites/default/files/GSO_RNM_GIS_Network.zip'

In [6]:
from invisibleroads_macros.disk import uncompress
from os.path import exists, join, splitext
from urllib.request import Request, urlopen

archive_path = '/tmp/greensboro-synthetic-network.zip'
archive_folder = splitext(archive_path)[0]
if not exists(archive_folder):
    if not exists(archive_path):
        request = Request(archive_url)
        request.add_header(
            'User-Agent',
            'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) '
            'Gecko/20100101 Firefox/15.0.1')
        r = urlopen(request)
        open(archive_path, 'wb').write(r.read())
        # urlretrieve(archive_url, archive_path)
    archive_folder = uncompress(archive_path)
source_folder = join(archive_folder, 'GSO_RNM_GIS_Network', 'Rural')

In [7]:
from invisibleroads_macros.disk import make_unique_folder
geometry_columns = [
    'geometry_layer',
    'geometry_proj4',
    'geometry_object']
target_folder = make_unique_folder('/tmp')

In [8]:
import geotable
from geopy import GoogleV3
from shapely.geometry import Point
g = GoogleV3('AIzaSyDNqc0tWzXHx_wIp1w75-XTcCk4BSphB5w').geocode
location = g('Greensboro, NC')
p = Point(location.longitude, location.latitude)
proj4s = open('proj4s.txt').read().splitlines()
target_proj4 = geotable.LONGITUDE_LATITUDE_PROJ4

In [9]:
source_path = join(source_folder, 'Line_N.shp')
t = line_table = geotable.load(source_path)

In [10]:
import numpy as np
from geotable.projections import get_transform_shapely_geometry

source_geometry = t.geometries[0]
target_geometry = p
best_index = 0
best_distance = np.inf
for index, proj4 in enumerate(proj4s):
    f = get_transform_shapely_geometry(proj4, target_proj4)
    distance = p.distance(f(source_geometry))
    if distance < best_distance:
        best_index = index
        best_distance = distance
best_proj4 = proj4s[best_index]

In [11]:
def save_geojson(target_name, source_name, target_columns):
    t = geotable.load(
        join(source_folder, source_name),
        source_proj4=best_proj4,
        target_proj4=target_proj4)
    target_path = join(target_folder, target_name)
    t[target_columns + geometry_columns].to_geojson(target_path)
    print(target_path)

In [12]:
target_name = 'line.geojson'
source_name = 'Line_N.shp'
t = geotable.load(
    join(source_folder, source_name),
    source_proj4=best_proj4,
    target_proj4=target_proj4)
target_path = join(target_folder, target_name)

In [13]:
t.iloc[0]

Code                    CLineaCable(CRamaEE(): RCLV3922->S_Dummy325)
NodeA                                                     S_Dummy325
NodeB                                                       RCLV3922
NomV                                                            0.42
Len(1c)                                                        0.034
TypeOU                                                             T
Equip                                         1P_OH_Runcina_TRPLX2/0
R                                                            0.01439
X                                                            0.00321
C                                                                  0
Imax                                                             265
FR                                                           0.00337
T_Rep                                                              6
Status                                                             1
InvC                              

In [14]:
t['id'] = ['l%s' % i for i in t.index]

In [15]:
data = t['NomV'].values.reshape(-1, 1)

In [16]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(1, 10))
scaler.fit(data)
scaler.transform(data)

array([[1.        ],
       [1.        ],
       [1.        ],
       ...,
       [2.58136483],
       [2.58136483],
       [2.58136483]])

In [17]:
t['width'] = scaler.transform(data)

In [18]:
t['width'].unique()

array([ 1.        ,  2.58136483, 10.        ])

In [19]:
target_columns = [
    'id',
    'width',
]
t[target_columns + geometry_columns].to_geojson(target_path)
target_path

'/tmp/RBebXPeUF9/line.geojson'

In [20]:
assets = []

In [21]:
for index, row in t.iterrows():
    id = row['id']
    assets.append({
        'id': id,
        'name': 'Line %s' % index,
        'typeId': 'l',
    })

In [22]:
ls $source_folder/*.shp

/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/DistribTransf_N.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/DummyEquip.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/HVMVSubstation_N.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/Line_N.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/Network_NEW_branches.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/Network_NEW_nodes.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/Network_nodes.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/NewConsumerGreenfield_N.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/StreetMap_branches.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/StreetMap_nodes.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/SwitchingDevices_N.shp
/tmp/greensboro-synthetic-network/GSO_RNM_GIS_Network/Rural/Transformer_N.shp
/tmp/greensboro-synthetic-network/GS

In [23]:
target_name = 'meter.geojson'
source_name = 'NewConsumerGreenfield_N.shp'
t = geotable.load(
    join(source_folder, source_name),
    source_proj4=best_proj4,
    target_proj4=target_proj4)

In [24]:
t.iloc[0]

Code                                                     RCLV2
Phases                                                       1
NVoltLev                                                   CBT
NVolt_kV                                                  0.42
DemP_kW                                                   0.76
DemQ_kVAr                                                 0.37
Subest                                          S_nSSEE1_12.47
Feeder                           S_nSSEE1_12.47 -> S_nCCTT2619
Pinst_kW                                                  1.89
Qinst_kVAr                                                0.92
RArea_m2                                                     0
NumLev                                                       1
Yearly_kWh                                                4147
NumCust                                                      1
geometry_object    POINT (-79.63002659266567 36.2809205913053)
geometry_layer                         NewConsumerGreen

In [25]:
t['NVolt_kV'].unique()

array([ 0.42, 12.47])

In [26]:
# I think this is peak demand in kilowatts
t['DemP_kW'].unique()

array([  0.76,   1.66, 139.55,  38.25,   2.74,  16.11,  40.74])

In [27]:
t['id'] = ['m%s' % i for i in t.index]

In [28]:
data = t['DemP_kW'].values.reshape(-1, 1)

In [29]:
scaler = MinMaxScaler(feature_range=(1, 10))
scaler.fit(data)
scaler.transform(data)[:5]

array([[ 1.        ],
       [ 1.05836155],
       [ 1.05836155],
       [10.        ],
       [ 1.05836155]])

In [30]:
t['radius'] = scaler.transform(data)

In [31]:
t['radius'].unique()

array([ 1.        ,  1.05836155, 10.        ,  3.43108293,  1.12839542,
        1.99538872,  3.5925499 ])

In [32]:
target_path = join(target_folder, target_name)
target_columns = [
    'id',
    'radius',
]
t[target_columns + geometry_columns].to_geojson(target_path)

'/tmp/RBebXPeUF9/meter.geojson'

In [33]:
for index, row in t.iterrows():
    id = row['id']
    assets.append({
        'id': id,
        'name': 'Meter %s' % index,
        'typeId': 'm',
    })

In [34]:
target_path = join(target_folder, 'assetById.json')

In [35]:
# import json
# with open(target_path, 'w') as f:
#     json.dump(assets, f)

In [37]:
import pandas as pd

In [39]:
df = pd.DataFrame()

In [41]:
df.from_dict(assets).to_csv('/tmp/assets.csv', index=False)

In [36]:
print(target_folder)

/tmp/RBebXPeUF9


In [43]:
ls $target_folder -hl

total 6.4M
-rw-rw-r--. 1 rhh rhh 1.1M Feb 15 00:41 assetById.json
-rw-rw-r--. 1 rhh rhh 4.3M Feb 15 00:41 line.geojson
-rw-rw-r--. 1 rhh rhh 1.1M Feb 15 00:41 meter.geojson
